### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by JoomFX** [gantry/docs#1]
Guys, would you please add a much more detailed instructions for Particles creation?
Since the Particle is the main building block in Gantry5, it should be very well documented.

Yes, you already have a tutorial in the Advanced section in the Documentation, but for some people who are not very familiar with YAML, it will be quite difficult to create a Particle.

Can you just explain everything with as much details as possible and the most important thing - add more real life examples, meaning add more tutorials explaining who you can create a more advanced Particle. Thanks :)

**Comment by mahagr** [comment]
We will, but for the first beta we found that the most important documentation is to give them an idea how our admin works and how you can use it in the most efficient way.

I could write a book on particles; you really can do crazy things with them and fast. You should take a look into twig documentation in here: http://twig.sensiolabs.org/documentation -- we are all reading that documentation daily. Yaml is pretty simple as it's just array presentation in human readable format, so there's not much going on in there. But above yaml syntax, we are mostly using HTML5 conventions on our blueprints (form field definitions). So what works as html attribute usually works in the blueprints as well. There are some extra attributes, though, as having fields involves usually more than just the input field.

For real life examples, just take a look our existing particles. :)

**Comment by JoomFX** [comment]
I would spend couple hundred dollars on your book, honestly :D
Thanks @mahagr 

P.S.   But really, a blog post, in the Documentation or even a book on "Particles" will be greatly appreciated ;)

**Comment by RyanMPierson** [comment]
added https://github.com/gantry/docs/commit/b6828eb68507a092ceb97cabd83ef7ec6f7f4b4b

Can be viewed here: http://docs.gantry.org/gantry5/tutorials/overriding-particle-settings#overriding-particle-source-files

Will add more info as it becomes apparent.
