### ISSUE TITLE
Layout Manager - some suggested changes

### ISSUE THREAD

**Issue by kat05** [gantry/docs#10]
![g5docs_lm_1](https://cloud.githubusercontent.com/assets/5719486/7475857/aa25ce64-f30f-11e4-9102-1754f1313a18.jpg)

![g5docs_lm2](https://cloud.githubusercontent.com/assets/5719486/7475892/df847600-f30f-11e4-97a6-579eaf960a91.jpg)

![g5docs_lm3](https://cloud.githubusercontent.com/assets/5719486/7475949/2f4ecc6c-f310-11e4-9d8d-0d3f54706093.jpg)

**Comment by rhukster** [comment]
Kat, the best way to suggest these changes is to click on the "edit this page" link in the top-right, then edit them on github.  It will create a PR that ryan can review, and merge. thanks!
