### ISSUE TITLE
Collections need badly some documentation

### ISSUE THREAD

**Issue by newkind** [gantry/docs#101]
Collections which are a huge part of the particles are almost undocumented. We should change that and describe them nicely, otherwise no one will know how to use such things like `value` etc.

![kopx0cjge3xnfxgoe0jwhebdc2k515](https://cloud.githubusercontent.com/assets/1641534/15751318/fd2fa63c-28e9-11e6-98ae-b73f9a175eff.png)

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/tutorials/using-particle-collections

Collections got badly some documentation. :)
