### ISSUE TITLE
Custom Responsive Grids Documentation is Outdated

### ISSUE THREAD

**Issue by N8Solutions** [gantry/docs#103]
Opening this as per the request of @w00fz 

The documented syntax is out-dated and not reflecting the classnames/layout of the current version.

This documentation was added as a result of #50.

Tagging @leskiapo so he can follow this since he was the one brought this issue up in the Gitter chat.
:point_up: [June 4, 2016 5:20 AM](https://gitter.im/gantry/gantry5?at=57523b0b9be9c5b637f052cd)

**Comment by N8Solutions** [comment]
In the documentation for [Custom Responsive Grids in Content](http://docs.gantry.org/gantry5/advanced/responsive-content) the examples are still using some Gantry 4 classes. So now it is a mix of Gantry 4 and Gantry 5 classes in the examples. I remember when this document was first introduced there was a **css** style sheet that could be added to the **custom.scss** file so the examples could be used. Since then this page has undergone some changes and that style sheet is no longer listed. Since I worked with Gantry 4 I recognized the classes as belonging to Gantry 4 instead of Gantry 5 though others may not and might wonder why the styling isn't working. The code examples should be updated so they are using the proper classes that correspond with Gantry 5 and if they are not built in to Gantry 5 then a style sheet should be added once more. @w00fz & @RyanMPierson

**Comment by RyanMPierson** [comment]
Hello,

Thanks for shedding light on this. Working with @marktaylor46 to see if we can't update the examples so they're 100% G5-specific.

Give us this week to come up with something. Thank you again.

**Comment by RyanMPierson** [comment]
Hello, the examples have been updated. Sorry for delay. Holiday here in the USA and we were pretty busy at RT with a sale and theme release.

All excuses out of the way, we've updated the doc with new examples. Hope they help!

**Comment by N8Solutions** [comment]
@RyanMPierson Could you please take a look at #147. The code for example 2 has some small errors that I fixed in the pull request.  Thank you!

**Comment by RyanMPierson** [comment]
done and done, thanks!
