### ISSUE TITLE
Missing html and views directories 

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/docs#107]
For template files http://docs.gantry.org/gantry5/advanced/customizing-theme-files#template-files
There should be mentioned that we can override for Joomla html folder and for WordPress views folder in the table.

**Comment by w00fz** [comment]
Done, although I can't find an official Wordpress reference about `views`. Do you have a link?

**Comment by newkind** [comment]
Views is purely our thing, there's no required directory structure for themes in WP.

**Comment by w00fz** [comment]
The entry in the docs is not for required folder but mostly to let the developer know what's available.

I added `html` for Joomla, which is also optional, and allows to override components / modules. However I am not sure how this works in WordPress.

How and what can you override with `views` ? Do you have an example?

**Comment by Webthemer** [comment]
You can override everything that is in here https://github.com/gantry/gantry5/tree/develop/themes/hydrogen/wordpress/views

**Comment by DamirPecnik** [comment]
You can override everything that is in here .... These are basicy views like they are in html folder for joomla ... overrides for single.php, comments layout etc ....
https://github.com/gantry/gantry5/tree/develop/themes/hydrogen/wordpress/views
