### ISSUE TITLE
Gantry 5 Overview Guide by OSTraining - add link

### ISSUE THREAD

**Issue by shoulders** [gantry/docs#119]
Hi,

The Gantry 5 documentation is great as a reference manual but for noobies it can be confusing and not make much sense to a noobie as it does not really give an overview of how Gantry 5 Works.

I am not recommending changing the layout of the documentation site etc.. but rather, adding a link to the free guide to Gantry 5 by OSTraining some where on the doc site.

[An Introduction to Gantry 5 from RocketTheme](https://www.ostraining.com/blog/joomla/gantry5/)

This guide can be read online or an ebook downloaded for free by signing up to their newsletter.

This guide allowed me to fully understand the basics of Gantry 5 and then the official documentation all became clear.

P.S. The gantry documentation is the best written I have come across for any opensource software.

**Comment by mahagr** [comment]
I think we could do that as I'd love to take advantage of external resources made by our community. What do you think @FrugalGeek @w00fz @rhukster?

**Comment by shoulders** [comment]
these are the individual blog posts in the order they are in the ebook. The book is still a better resource to use.

[An Introduction to Gantry 5 from RocketTheme](https://www.ostraining.com/blog/joomla/gantry5/)
[How to Build a Joomla Site With Gantry 5](https://www.ostraining.com/blog/joomla/gantry-site/)
[Gantry 5: Particles, Atoms and the Layout Manager](https://www.ostraining.com/blog/joomla/gantry-layout/)
[Using the Menu Settings in Gantry 5](https://www.ostraining.com/blog/joomla/gantry-menu/)
[Gantry 5: Advanced Tips and Techniques](https://www.ostraining.com/blog/joomla/gantry-advanced/)

**Comment by RyanMPierson** [comment]
I'll get these added to an "External Resources" page tomorrow. Thanks!

**Comment by RyanMPierson** [comment]
I added the page here: http://docs.gantry.org/gantry5/basics/external-resources

This is being added as a test in hopes that folks with great tutorials and resources for Gantry 5 will step forward and add their own, but I fear that it'll very quickly turn into a link building tool for companies that want to use it to advertise their products and/or services.

We'll see how it goes! Thanks for the idea. :)

**Comment by JoomFX** [comment]
Hopefully, it will not turn into a link building tool.

After all, you guys are the ones who decide what should be published and what not.

**Comment by RyanMPierson** [comment]
Yah, we have that going for us. :) Feel free to submit any tutorials or whatnot you've written, @JoomFX.

**Comment by JoomFX** [comment]
Thanks Ryan :)

For quite some time I was planning to post a series of blog posts, something like "Gantry 5 Explained" but I do not think that I will find time for this in the near future.

My plan is to cover the whole process of building and configuring a website with Gantry 5 by comparing the workflows for all platforms (Joomla, Wordpress and Grav).
In my opinion there are very important things that need to be explained in more details:
1. When the user should drag and drop particles directly in the Layout vs adding them with the "Gantry 5 Particle" module/widget. What are the pros and cons of those two approaches.
2. How people in Joomla should modify the settings under the "Base" outline, not the "Default", if they want to apply something globally, to all pages. I do believe that there should be a paragraph in the documentation that explains why there is a "Default" outline and how it is different than "Base". Matias explained it very well in https://github.com/gantry/gantry5/issues/295
3. What exactly is the purpose of the "Particle Defaults" tabs and how it should be used. In the way I use Gantry 5, the only thing that I do under "Particle Defaults" is to change the website Logo in the "Logo/Image" particle.

As you know, with Gantry 5 a website can be build and configured in several different ways. This gives great freedom and flexibility but sometimes it might also be very confusing. In my opinion there should be a "best way" or "recommended way" of doing things in Gantry 5 which of course will vary for each platform :)

**Comment by shoulders** [comment]
These articles are the bridge between newbies and the the gantry 5 framework documentation. People will not find it on the external resources page as it has just been added as a reference with no recommendation to read them so the frustrated user might of given up before getting to the external resources page, I know I gave up until I came across the OSTraining articles as everything frustrated me because I did not know the names of things or why you would do certain actions.

to fix this  i would ask the following

1) add a note to http://docs.gantry.org/gantry5 or http://docs.gantry.org/gantry5/basics saying if you have not used Gantry before read these as they will explain a lot of newbie issues before reading the documentation.

2) on the page http://docs.gantry.org/gantry5/basics/external-resources under the OSTraining title I would add a paragraph explaining that all new users of Gantry 5 should use this as it gives an overview of the whole system and will explain a lot of things.

I write this speaking as a newbie who struggled to get his head around Gantry 5 from just reading the docs and I do have experiences at programming.

My idea of these links, not necessarily a external resource page (which is a good thing) was to simply bridge the gap between newbie and useful Gantry User.

thanks

nb: as an end user I do appreciate the amount of time people put into this project.

**Comment by RyanMPierson** [comment]
I hear you, but wouldn't it be easier to improve the documentation itself instead of leaning on a third party company's webpage to provide that information?

We also have no control over these webpages. They could become a 404 without notice leaving our documentation broken.

I'd much rather hear suggestions to improve what we have. External resources are useful and great to have, but they're inherently limited. Our documentation is growing constantly. I've added several new pages and edited many others this week alone.

If we put a notice on the home page of the docs to go somewhere else for documentation, what would be the point of our documentation?

I would love to hear any issues you've been having with our docs. Where you feel you got stuck, specifically. I can add more info very easily. You can also edit the docs yourself to add tips and tricks as you come across them on GitHub.

**Comment by shoulders** [comment]
@FrugalGeek 

It would be great if the documentation included an overview of Gantry which is exactly what this course does and the official documentation does not. The official documentation is a reference guide rather than a tutorial.

I understand you guys do not have control over 3rd party sites and they could 404 at anytime. OSTraining has worked with RocketTheme as a partner in the past so i dont think these are going anywhere. You could even offer to allow downloading of the PDF on docs.gantry.org if they signup to OSTraining.

So for improvements to the docs.gantry I would recommend exactly what is in the OSTraining course, an overview of what Gantry is and how it works for the end user. The reason I say use the OSTraining course is that is is already written and is great. An overview is a tutorial for the end user with a sprinkling of developer stuff which then leads to the normal docs.gantry site etc...

On the http://docs.gantry.org/gantry5 or http://docs.gantry.org/gantry5/basics page I would have a note at the top

> If you are new to Gantry you might want to look at this series of articles from OSTraining as docs.gantry is a reference manual for developers - add to external resources links page here

on the page http://docs.gantry.org/gantry5/basics/external-resources the paragraph would something like

> These simple to follow articles will go over the basics of how the Gantry framework works with Joomla so you as an end user can understand all of the basic terms and features of this software. This course is aimed at the end user of this software but is also useful for developers to get a feel for how Gantry 5 works.

Before I got involved with GitHub I got in contact with RocketTheme and mentioned this hole in the documentation, later I discovered the OSTraining stuff and the rest is history.

@JoomFX

I also think it would be a good idea to have some tutorials on practical usage of Gantry 5 as not everyone is a coder and just wants to setup a nice website from within the CMS environment.

**Comment by RyanMPierson** [comment]
@shoulders I hear you. I created the http://docs.gantry.org/gantry5/basics/introduction for that very purpose. But I understand it isn't as complete and detailed as the one OSTraining put together.

Give me the weekend to add some more content on the docs to this end.

You should also know that I'm working on a larger video series of smaller tutorials. We've been working on getting Grav implemented before putting everything in stone on camera, but we're actually at a point where additions and changes are pretty much locked in.

I'll comment again when I have some changes in. At that point, let me know how you feel about it, if there are specific additions you'd make, and we'll take it from there.

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/basics/introduction

I've rewritten a lot of this page to include some more tutorial-like information. I'm in the process of adding screenshots to enhance the material now. If you have any additions or suggestions for this page please feel free to submit them or let me know.

**Comment by shoulders** [comment]
I will have a look at weekend and give you some feedback, sorry i cant do it before then.

**Comment by shoulders** [comment]
I wrote an introduction page (the introduction bit to explain what gantry is)  using the stuff you wrote, github description and me. it gets mangled here. Is there anywhere I can send it?

**Comment by RyanMPierson** [comment]
You can add it to a branch of the docs project and link it here. We can look at it, refine it, and merge it into the live docs.

**Comment by shoulders** [comment]
it is not in markdown and I have no idea yet how to add a branch with github :(

it is a word document currently.

Can I email it to you?

**Comment by RyanMPierson** [comment]
Sure. ryan at rockettheme.com

Thanks!

**Comment by shoulders** [comment]
sent.

sorry it took so long to get back to you I got a bit carried away with another project.

If it needs tidying up let me know.
