### ISSUE TITLE
Layout Manager - Offcanvas Section needs a new screenshot

### ISSUE THREAD

**Issue by kat05** [gantry/docs#12]
http://docs.gantry.org/user/pages/01.gantry5/03.configure/04.layout-manager/offcanvas_4.png
needs to be updated after the following ticket has been fixed:

https://github.com/gantry/gantry5/issues/187

**Comment by FrugalGeek** [comment]
This does not appear to have been fixed. Both on my synced local copy and staging it appears with the same issue.

**Comment by RyanMPierson** [comment]
Updated! Thanks!
