### ISSUE TITLE
Display Related Posts

### ISSUE THREAD

**Issue by warisaajkal** [gantry/docs#125]
How to display related posts on single post in WordPress.
I have tried to override "views/partials/content-single.html.twig" file I want to show related post after content but I don't know related post code in above mention file.
advance thanks

**Comment by RyanMPierson** [comment]
Related posts are indeed a common and popular choice for WordPress sites. However, this is so much easier to do in the form of a widget using one of the dozens of plugins already available on the market. You can create a widget position in the layout and apply the related post widget as you would any other widget in wordpress.

Accomplishing this within the theme is doable, but we do not have plans at the moment to add that specific tutorial to the Gantry documentation as it relates to a specific CMS in a specific use case. One that would be rare.
