### ISSUE TITLE
Custom Link menu item not showing

### ISSUE THREAD

**Issue by Roadsider** [gantry/docs#143]
I'm using Hydrogen on Wordpress, and I attempted to create a Custom Link menu item in the top level. Doing so did not make it appear in the Hydrogen menu editor. As there were also submenu items, those didn't show up either. Is there a known problem?

**Comment by Roadsider** [comment]
I want to add that this system continues to be broken. I brought this up previously, and it seemed that it was given priority. Unfortunately, changes made in the Menu Editor not only are not reflected in Wordpress Menu Appearance, it also produces completely unpredictable behavior. 

I attempted to delete a menu item in the Menu Editor. While that item was deleted, the Editor also deleted a different item and added a sub-menu item from different top-level menu item. This is disastrous for me. 

![screenshot 2017-03-09 11 35 36](https://cloud.githubusercontent.com/assets/4763933/23760084/9881294a-04bc-11e7-81b8-87a965458372.png)
![screenshot 2017-03-09 11 35 23](https://cloud.githubusercontent.com/assets/4763933/23760085/9882302e-04bc-11e7-9df6-4d849b5c9747.png)



Screen shots enclosed.

**Comment by RyanMPierson** [comment]
This issue is not documentation related and appears to have been resolved in further updates. Closing this issue.
