### ISSUE TITLE
Chrome HTML Styling

### ISSUE THREAD

**Issue by pleavin** [gantry/docs#148]
Hi,

In the Gantry 5 Documentation there is no explanation of what Chrome HTML Styling is or how to use it. It's also next to impossible to Google an explanation of what this is given the name of one particular popular browser... 

I was eventually able to find this information in the Gantry 4 documentation.

Unless Chrome HTML Stylizing is being retired, I'd recommend to migrate/copy some of the key explanations from the Gantry 4 documentation to the Gantry 5 documentation. If it being retired, it would be nice to get some "don't worry about!" text next to the places where it is referenced.

**Comment by mahagr** [comment]
Chrome has nothing to do with Google or even with styling, at least if you think of CSS.

Module Chrome is something which is used in Joomla (and WP, though by using another name) as an HTML wrapper around the module. You could use table, divs, lists etc to wrap around the modules. Or you could remove the HTML altogether. The feature is still there, but it's really not that useful anymore as you can do almost all of it with simple CSS3. Gantry 5 provides a single chrome option out of the box, it's called "gantry" and you can see it in module positions.
