### ISSUE TITLE
Particles configuration / cache in YAML

### ISSUE THREAD

**Issue by w00fz** [gantry/docs#152]
Configuration and caching settings at particle level was added but we do need this to be documented.
What is it, how it works and what are the options that can be used.

reference: https://github.com/gantry/gantry5/commit/8eddeb43c3fdc3ab7105d0eb6beb785e7a54c1de#diff-687da5a81d1e4c326c9627e5ba6008ad

@mahagr can you please write a quick summary about all that? Also since you had to change every particle to use static, couldn't we just default to that rather than explicitly defining it?

Thanks

**Comment by RyanMPierson** [comment]
Awesome. Will get to it next.

**Comment by mahagr** [comment]
There's really only one caching mode (aside for not caching/being dynamic): static. I also added menu, but it has still some issues with some configurations, so it's not being used.

Static caching is permanent caching which only takes account of particle configuration. Basically, it caches the particle until the configuration of the particle changes.

Static caching only works for particles which have no changing content. You cannot cache particles with a date in it, nor can you cache any particles, which use platform content or methods with changing values. This is why caching has been disabled by default.

For changing content, I need to add caching with a timeout. The support is kind of there already, I've just not had time to add and test it out.

**Comment by thexmanxyz** [comment]
@mahagr @w00fz I have a question on the static caching configuration because I'm not 100% sure what is actually does. Are only the values of the particle cached or is any content generated by the particle cached? Let's assume a particle with static configuration values that generates dynamic content e.g. from Joomla or fetched from a JS API. Is in this case the dynamic content cached or is it written out as it is?!

**Comment by mahagr** [comment]
Basically the static caching caches the particle instances by configuration. If configuration changes, new cache key is used and the instance gets updated in the page. Nothing else affects the caching and there's no specified timeout on the cache.

So static means that it'll be cached (up to) indefinitely and only either clearing cache or changing the configuration of the particles clear the cache.

**Comment by thexmanxyz** [comment]
@mahagr thanks for your answer. So static caching should only be used for particles that display completely static content? Am I understanding that right? So dynamic content generated by an API would be cached the first time the particle is loaded and then kept until the particle configuration changes or the cache is cleaned? sorry for my demand but I want to clearly understand when to use it and when not :)

**Comment by mahagr** [comment]
Yes, it should only be used when there are absolutely no changes from view to view. Caching gets disabled in development mode, BTW.

**Comment by thexmanxyz** [comment]
@mahagr Alright :). Thanks for you patience!

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/particles/particles#caching

**Comment by mahagr** [comment]
Looks good!
