### ISSUE TITLE
Wrong Parameters - addScript()

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/docs#153]
Hey there,
I found out that there is a wrong syntax listed for the *addScript()* method in the documentation at **01.gantry5 / 05.advanced / 08.css-js-twig**. However I will prepare a pull request and udpate the wrong syntax because I tried to use this method and wondered why it does not work correctly. 

I didn't check the whole file so there may be other errors on this site too. That's also the reason I opened an issue and do not only create the pull request. Please review this page if there are additional issues. <del>As soon as I created the pull request I will put a reference here and back from the pull request.</del> See also #154.

**Comment by mahagr** [comment]
You were right.
