### ISSUE TITLE
G5 directory structure

### ISSUE THREAD

**Issue by humblehumanbeing** [gantry/docs#19]
G5 installs into separate directories.
We need to know which file/dir is where.
A G5 directory structure with respect to Joomla installation would be helpful.

**Comment by RyanMPierson** [comment]
A theme directory matrix is already included here: http://docs.gantry.org/gantry5/advanced/customizing-theme-files#theme-directory-matrix

If there are file(s) in particular you'd like to have highlighted, we can oblige.
