### ISSUE TITLE
Preset creation

### ISSUE THREAD

**Issue by JoomFX** [gantry/docs#2]
Hey guys,

Would you please include detailed instruction for "Preset" creation?
Since it is YAML as well, it is not that obvious (eventhough it is a simple language that describes data) :)

I'm talking about the following:

![alt](http://i.imgur.com/fYgwf1L.png)

Basically, the user needs to create a YAML file in the "layouts" folder but there are quite some parameters that need to be explained with as much details and examples as possible. The "Test" preset file is quite simple but in the "home.yaml" file there are some confusing parts :)

Thanks ;)

**Comment by RyanMPierson** [comment]
This is a great idea, and it is certainly something we have on the list. As the beta development continues, a lot of the processes we could document right now will likely change before the full release.

There is good news, however. We plan to have a lot more presets built in to cover the vast majority of use cases. Multiple sidebars, options with a few or a great deal of sections, etc. are use cases we're aware of and we hope to have solutions in place to facilitate these needs.

**Comment by RyanMPierson** [comment]
Done and done! 

Viewable:
http://docs.gantry.org/gantry5/advanced/creating-layout-presets
