### ISSUE TITLE
How to add a section

### ISSUE THREAD

**Issue by pambesteder** [gantry/docs#25]
I would think this would be easy to know.  But in watching the video on the Layout Manager....it doesn't say.  Nor can I find it in the documentation.

In the video, there's a section for FEATURE.  My question is how do I create a section in my layout for a feature or for a showcase, etc.?

Thanks
Pam

**Comment by ghost** [comment]
If you carefully read the docs, you will find: http://docs.gantry.org/gantry5/advanced/creating-layout-presets

Is the same for every section, you can just copy `header` for example and replace `heder` with any name you like,

**Comment by pambesteder** [comment]
Thank you...yet...this doesn't help me.  I'm not a techie list most and don't understand all that the documentation is showing.  It's written assuming people already know what it all means.  Thanks anyway...I'll keep trying to find instructions/directions that will help me.  Thanks

**Comment by pambesteder** [comment]
Here's what I mean.  In the documentaiton it says...

It is very easy for a SKILLED DEVELOPER to create a Layout Preset. This is a great way to take an existing Layout Preset and add or remove Sections to it, or to build an entirely new Layout Preset from scratch, if you are so inclined.

I'm not a skilled developer and chose this template because it said no experience necessary and you can drag and drop to create the layout.  I don't mind learning what to do...yet as I said the documentation is written as if people already knew what to do.  Thanks so much

**Comment by ghost** [comment]
Is drag and drop in layout manager, there are few presets, but as for any other template, if you are not pleased with that one and you want  a more deep custom work, you need to write some code, although is not hard to do that.

 All you need to do, is to navigate to `custom` folder, and in that folder create another folder named `layouts` then create a new file inside `layouts folder` `mylayour.yaml` so it need to be `.yaml` file, in that file you can add this code, just copy and paste: https://gist.githubusercontent.com/adi8i/c5e07b9edbc7e98d7775/raw/313267ad0a21a77af31af16c2db22e98c6455460/simple-layout.yaml

In future maybe will be possible to create a new layout preset from `layout manager` too, but for now are other things to do. 

So in the end you will have `custom/layouts/mylayout.yaml`

**Comment by pambesteder** [comment]
Now THAT is exactly what I was looking for.  Steps on what to do and where to go! That kind of instruction would be nice in the documentaiton.  I'm not the sharpest tool in the tool shed and can figure things out of I'm giving a nudge in the right place. THANK YOU!

**Comment by pambesteder** [comment]
The template I'm using is the Hydrogen-Default.  Will copying in this code automatically make those sections show up in the Hydrogen-Default template???

**Comment by ghost** [comment]
Hydrogen-Default is what we call an `outline` so basically the template. Layout Preset is another thing, you need to click `hydrogen-default` then navigate in layout manager, hit Load button, and select a preset.

I did not understand too well your question :).

**Comment by pambesteder** [comment]
Yes, that helps, thank you.

**Comment by jwwicks** [comment]
Note that if you are using Multisite the directory will be slightly different:

THEME_DIR/custom/blog-#/layouts/mylayout.yaml

where blog-# is the id of the site, such as blog-5.

**Comment by jwwicks** [comment]
As an added note, if you are say copying a section and just renaming, you'll also have to copy the yaml file from the blueprints/styles directory for that section or you won't see the fields in the Section Styles in the Styles tab for your Outline. Each section has a corresponding yaml definition so just copy and rename it to match the section you just created/copied.

So say I copied the testimonials section and named it "leadership" in my new Layout. I'd copy the THEME_DIR/blueprints/styles/testimonials.yaml file to THEME_DIR/custom/blueprints/styles/leadership.yaml or to THEME_DIR/custom/blog-#/blueprints/styles/leadership.yaml if you're using WP Multisite.
