### ISSUE TITLE
Is the custom.css the same as in Gantry 4?

### ISSUE THREAD

**Issue by pambesteder** [gantry/docs#26]
I learned how to create a custom.css in my Gantry 4 template for overrides.
Is the process the same in Gantry 5?  Do I manually create a custom.css file and if so...is there a special place I need to include it?

**Comment by w00fz** [comment]
It's explained in the [Docs Site](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet), the page you can find also [here on GitHub](https://github.com/gantry/docs/blob/develop/pages/01.gantry5/04.tutorials/02.adding-a-custom-style-sheet/docs.md).
