### ISSUE TITLE
Renaming the default G5 Template (Hydrogen)

### ISSUE THREAD

**Issue by JoomFX** [gantry/docs#3]
Can you please add a "Renaming the default G5 Template" section in the Documentation, explaining all the steps that need to be performed?

There are many files that need to be edited in order to properly rename it:
1. templateDetails.xml - apart from the general info on the Top, the developer needs to edit line 40 as well:

```
<fields name="params" addfieldpath="/templates/g5_hydrogen/fields">
```

Apart from that, should we just delete the `<updateservers>` section at the bottom if we do not have a live update server?
1. I suppose the language strings in the "install.php" and "..fields/warning.php" should not be edited, should they?
2. "..gantry/theme.yaml" - there are really a lot of instances of the "hydrogen" word. How should we handle this file?
3. Edit all files in the "../blueprints/styles" directory and change the `description`?
4. Rename the language files in "..language/en-GB" to reflect the template name.
5. And of course, rename the whole "g5_hydrogen" directory.

Guys, such chapter in the Documentation is really needed. Please consider this.

P.S.   I'm really interested what you will do with the SCSS files. Will you rename each and every directory and file so it reflects the Template name or you will leave them "Hydrogen"?

**Comment by mahagr** [comment]
First 2 betas mostly consendrate on administration and basic usage. We will improve documentation as fast we can, but there are so many things to be done.. :)

During the next few weeks we start consendrating on building templates, so documentation will surely follow as we need it ourselves!

**Comment by JoomFX** [comment]
Great! Thanks @mahagr .

I opened this issue just to have it as a reminder, because there is no such information in the Gantry4 Documentation for example.

We really need such thing in the Documentation ("Renaming the default G5 Template").

Of course, there are much more serious issues that need to be addressed first :)

**Comment by RyanMPierson** [comment]
Added enhancement label to make it easy to spot this as an additional documentation request. Will revisit this after the next beta comes out and we have a more permanent workflow in place for this.

**Comment by Hertak** [comment]
I use the inbuilt joomla feature to copy the template and i´m testing with no problem

**Comment by mahagr** [comment]
@Hertak I need to check it out to make sure everything works on that. :)

**Comment by nicutor** [comment]
+1 for this. We really need this docs.

**Comment by RyanMPierson** [comment]
Done and done.

As with any doc, there may be additional information added after the fact. http://docs.gantry.org/gantry5/theme-development/change-theme-name

Thanks for the suggestion. This request also inspired the addition of a Theme Development chapter in documentation, where guides that relate to new theme development will go.

**Comment by JoomFX** [comment]
Thank you, thank you and thank you :D

Seriously Ryan, thank you very much!

**Comment by kmbt** [comment]
Hi,
I have written a Python script that may be of help when renaming the Hydrogen theme. It replaces all occurrences of string such as "hydrogen" in theme zipfile whether lowercase, uppercase or capitalized. The replacement is done in file contents as well as in paths. After initial tests it seems to work well. I think that you may find it useful for the renaming process.

Edit:
I forgot to paste paste a link. Here it is: https://github.com/kmbt/hydrogen-renamer
