### ISSUE TITLE
Using Media Queries

### ISSUE THREAD

**Issue by w00fz** [gantry/docs#33]
Like described in the blog post for RC3, we now have a new breakpoint dedicated to the Mobile Menu only. Should probably be included and described in the Using Media Queries tutorial *([pages/01.gantry5/04.tutorials/10.media-queries/docs.md](https://github.com/gantry/docs/blob/develop/pages/01.gantry5/04.tutorials/10.media-queries/docs.md))

**Comment by RyanMPierson** [comment]
Let me know if the example CSS is accurate. If so, resolved! huzzah!

**Comment by w00fz** [comment]
Yes looks good.
