### ISSUE TITLE
Fixed Nav and some warnings 

### ISSUE THREAD

**Issue by ghost** [gantry/docs#35]
Hello there @FrugalGeek  i wrote a tutorial about fixed nav with headroom.js, if you like, feel free to adapt and include it in docs, i am sure there are some grammatical mistakes also, you can also exclude headroom.js part, so will be a simple fixed nav, is up to you. 
http://muvingup.com/en/docs/gantry-5/19-gantry-5-fixed-navigation-with-headroom-javascript

Because i see many people on gitter chat, that try to add css code in `css-compiled` folder and so on. Should be added some warnings in docs  `don't to this`.  Don't modify any file in css-compiled folder... things like this you know, just include them as notes, in articles where's needed.

**Comment by RyanMPierson** [comment]
This is great! I'll get it added soon. Just have to go through it, test on my end, and give it some edits.

I'm working on RC3 updates at the moment, so this will get done right after.

**Comment by RyanMPierson** [comment]
Per our conversation on Gitter, I'm incorporating parts of your tutorial into a larger "bringing it all together" document that utilizes multiple techniques outlined in the doc guides.

A warning against editing css-compiled is already in place here: http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet#dependenciesscss
