### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by max123kl** [gantry/docs#36]
Hi,
I recently started to tanslate the Gantry5 docs to german.

As I'm no prof. translator nor an IT specialist, first of all,  I do it for personal use. 
But if there is any interest to integrate it in your docs, have a look at https://github.com/max123kl/docs_de_DE

I'm not familar with Markdown and Github so I hesitate to issue a pull-request.

I did rename the repo, cloned it to local, and added a new branch in which the translations are made and pushed it bach to my account. 
Are there any further suggestions or advises?
In particular the followin phrase needs a bit additional explanation:
"Every change must pass through the staging branch first, so please ensure your pull-requests are directed to the proper branch."

**Comment by RyanMPierson** [comment]
Wow, this is quite an undertaking. You should be aware that the docs are always changing. Even today I have four of five changes on the list, with more coming as we approach 5.0.0 (first full release). I'm touching base with the rest of the team to see if/how we can incorporate this. 

Thanks! This will undoubtedly be useful for the many German-speaking users out there.

**Comment by max123kl** [comment]
[quote]
You should be aware that the docs are always changing.
[/quote]
This will be a challenge. 
I guess how to get my local develop branch synced with yours.
A `git fetch upstream` did not work in the expected way.

I think I will continue translating with the installing procedure and go further with the HowTo chapter. Or are there any other priorities?

**Comment by RyanMPierson** [comment]
Going to close this issue, however this is a great initiative. Since it would be so difficult to keep up with maintaining the two languages and keeping them in sync, we are sticking with English for the official documentation for now. However, we'd totally be open to linking to your site if you chose to host/maintain them on your own.
