### ISSUE TITLE
WP version of path in Overriding Particle Settings is needed

### ISSUE THREAD

**Issue by newkind** [gantry/docs#38]
Right now we have this in the Overriding Particle Settings 

`The first thing you will need to do is copy the copyright.html.twig and copyright.yaml files located in ROOT/media/gantry5/engines/nucleus/particles/ and paste the copies to TEMPLATE_DIR/custom/particles. If the particles directory does not already exist in your custom folder, you will have to create it.`

We need a WP path to the copyright.html.twig and copyright.yaml files

**Comment by RyanMPierson** [comment]
There are a lot of platform-specific paths throughout documentation which will be addressed when we have a WP Gantry 5 theme I can actively test with up and running. Coming soon!

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/tutorials/overriding-particle-settings#overriding-particle-source-files

It's live!
