### ISSUE TITLE
mobile menu doesnt display in Opera mini browser in mobile

### ISSUE THREAD

**Issue by sujansiddhi** [gantry/docs#39]
The mobile menu cannot be seen in mobile(Opera mini browser). but you can get the menu by clicking the 'blank space', where the menu should have been displayed. Clicking the blank space shows off- canvas menu

**Comment by RyanMPierson** [comment]
Are you experiencing this problem in the Gantry 5 documentation, or when using a Gantry 5 theme? Also - Which mobile OS and Opera mini browser version are you running?

**Comment by RyanMPierson** [comment]
Closing issue. We tested and were unable to replicate issue.

**Comment by RyanMPierson** [comment]
Reopened: Was able to replicate the issue on Opera Mini for Android (in Android Lollipop).

Appears to be a known FontAwesome compatibility issue as the missing bits and pieces are all FontAwesome icons.

**Comment by rhukster** [comment]
Works fine for me in latest opera on iOS.  Seems like perhaps Android version has not been updated yet?

**Comment by kat05** [comment]
I can confirm that there is an issue with FontAwesome icons on Opera Mini (installed today) on Android 5.1, on a Samsung Galaxy S4.
The icons won't load either on the official FontAwesome site, please see pic.
![screenshot_2015-07-19-11-35-07](https://cloud.githubusercontent.com/assets/5719486/8765412/0514b2fa-2e0b-11e5-9fb5-1c7384d05aef.png)
![screenshot_2015-07-19-11-32-57](https://cloud.githubusercontent.com/assets/5719486/8765411/0513e7a8-2e0b-11e5-977f-afd197e315c9.png)

**Comment by RyanMPierson** [comment]
Problem appears to be with Opera Mini browser not supporting the font. Closing for now, but noting in the event that a workaround is made available in the future.

Also, submitting a bug report to Opera through its feedback channel so they are aware (and in the event that a non-destructive workaround is available).
