### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ghost** [gantry/docs#43]
There should be something in Gantry 5 documentation that explains the position with Android browsers and what we can and can't support. Or at least some rationale that explains why this is so difficult (e.g.distros, manufacturers, physical devices, lack of updates, etc, etc).

This issue came about because a member reported the mobile menu not working on our demos (2nd level menu) member was using Android 4.1.2 and Firefox for Android 39 (latest). see https://github.com/gantry/gantry5/issues/557

**Comment by RyanMPierson** [comment]
Fixed!
