### ISSUE TITLE
Typo in "Creating a New Particle" tutorial.

### ISSUE THREAD

**Issue by surfarcher** [gantry/docs#45]
Chapter: 5. Advanced
Part: 1. Creating a New Particle
Section: [Pulling Gantry Configuration Data Using Twig](http://docs.gantry.org/gantry5/advanced/creating-a-new-particle#pulling-gantry-configuration-dat)

Paragraph 3:

> Pulling a configuration varialbe is pretty easy. You just need to use the gantry.config.get() command to pull this data.

The fourth word "varialbe" should be "variable".

**Comment by RyanMPierson** [comment]
Fixed. Thanks so much for your keen eye. We appreciate it!

If you would like to make the edits directly to the file in GitHub you can receive commit credit for the change. It's actually less steps than sending an issue report.
