### ISSUE TITLE
Add documentation on how to load css / js from twig

### ISSUE THREAD

**Issue by mahagr** [gantry/docs#49]
I just added new functions (you may add "since Gantry 5.0.2"):

If you want to add javascript and/or css from your twig file, you can do something like this:

```
{# Add assets into head of the document by using default priority. #}
{% assets in 'head' with { priority: 0 } %}
    <link rel="stylesheet" href="{{ url('gantry-theme://css/my.css') }}" type="text/css"/>
    <style>
        body {color: red}
    </style>
    <script type="text/javascript" src="{{ url('gantry-theme://js/my.js') }}"></script>
    <script type="text/javascript">
        var MY_VAR = 'test';
    </script>
{% endassets -%}
```

Basically assets can take two optional parameters:
- in 'x'
- with { priority: y }

where `x` is the location you want to add your stuff (`head` and `footer` are currently supported by Hydrogen theme) and `y` is priority, which is used to order the assets defaulting to 0 and being in range of -10 ... 10. Priority with higher number gets added into the document before any lower number. If there are multiple assets tags with the same priority their ordering is undefined.

There is also a twig tag for javascript only:

```
{# Add javascript into end of the document (before any other javascript in the footer). #}
{% scripts in 'footer' with { priority: 10 } %}
    <script type="text/javascript" src="{{ url('gantry-theme://js/footer.js') }}"></script>
    <script type="text/javascript">
        var MY_VAR = 'test';
    </script>
{% endscripts -%}
```

And for stylesheets only:

```
{# Add some stylesheets and make them to load last (override other styles). #}
{% styles with { priority: -10 } %}
    <link rel="stylesheet" href="{{ url('gantry-theme://css/my.css') }}" type="text/css"/>
    <style>
        body {color: red}
    </style>
{% endstyles -%}
```

**Comment by mahagr** [comment]
Advanced: You can also add your custom locations where you can output your styles and scripts

```
{{ gantry.styles('styles')|join("\n    ")|raw }}
{{ gantry.scripts('scripts')|join("\n    ")|raw }}
```

After defining the locations, you can add stuff into them just like with `head`and `footer`:

```
{# Add javascript into your custom location. #}
{% scripts in 'scripts' %}
    <script type="text/javascript" src="{{ url('gantry-theme://js/script.js') }}"></script>
{% endscripts -%}
```

**Comment by RyanMPierson** [comment]
Added this guide. Would like to expand on it with practical example that breaks it down for newer developers in the future.
