### ISSUE TITLE
Migration from G4

### ISSUE THREAD

**Issue by humblehumanbeing** [gantry/docs#5]
Assume we have a Joomla installation with modules of G4 positions.
As you know @Omegatcu has recently added a G4 layout to the G5 dev branch.
Can you please prepare a Youtube video about how we can view G4 modules on this newly-added G5 layout?

**Comment by ghost** [comment]
You need to load this template in Layout manager, then check the module positions, so just make sure the modules are placed in right position. 

You can also rename the positions, from `layout manager` - `module position settings` - `key` .
![capture](https://cloud.githubusercontent.com/assets/9744973/7369752/1a1fb160-edbd-11e4-96d7-c0be9d7dc1fa.PNG)

You can find some info here http://docs.gantry.org/gantry5/configure/layout-manager. 
And also would be nice to have some videos, @FrugalGeek  is already working on videos, so later on may be you will have this kind of video.

**Comment by ghost** [comment]
PS: don't count how many times i said video :laughing:

**Comment by ghost** [comment]
But the final result may be slightly different because g5 use other css config. etc, so you will be busy few houres :D

**Comment by humblehumanbeing** [comment]
@adi8i Thanks

**Comment by RyanMPierson** [comment]
I'll add this one to the list. Good idea.

**Comment by RyanMPierson** [comment]
Added a quick doc addition to two different pages in documentation:

http://docs.gantry.org/gantry5/particles/particles#positions
and 
http://docs.gantry.org/gantry5/particles/position#creating-deleting-and-moving-pos

So they should be easy to find. Will keep the video suggestion in the list for a long-form demonstration of migrating from G4 to G5. Thanks!

**Comment by humblehumanbeing** [comment]
In fact a long time has passed since the 1st release and I am now more familiar with G5. I no longer need such a doc. Thanks.
