### ISSUE TITLE
Suggestion: improve documentation on "production/development" mode

### ISSUE THREAD

**Issue by ghost** [gantry/docs#51]
http://docs.gantry.org/gantry5/configure/extras#development-and-production-modes

The documentation for "production/development" mode should be improved to explain the effect that it has on hash values(asset timestamps) and the "system - Gantry 5" plugin also explain timestamp period and give practical suggestions for usage and good settings. At the moment the docs only say it affects when custom.scss is compiled yet it already does more than this.

Please note that the screen print in the documentation is also out of date as it does not show the timestamp fields (although this might be because perhaps they are only in the CI build?)

![2015-08-11_14-15-49](https://cloud.githubusercontent.com/assets/11683218/9198388/acb055e8-4033-11e5-8848-ceb5fc9e35eb.png)

**Comment by RyanMPierson** [comment]
Resolved on https://github.com/gantry/docs/commit/d9e3ab501fa59e5708fabcfb4b890f3a6bc3eb4e
