### ISSUE TITLE
List and description of Nucleus' utilities available

### ISSUE THREAD

**Issue by w00fz** [gantry/docs#54]
We should add a dedicated page to nucleus' utilities where we list all of the ones that are available.
Things like `visibile-phone`, `hidden-desktop` you really need to go search for and are not written anywhere afaik.

ie, https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/scss/nucleus/_utilities.scss

**Comment by RyanMPierson** [comment]
Committed in https://github.com/gantry/docs/commit/4078a5d9f8b5cf7c11bed1d9b790be2668614e40
