### ISSUE TITLE
Typo in the docs (System Messages and Page Content)

### ISSUE THREAD

**Issue by JoomFX** [gantry/docs#66]
Hey @FrugalGeek ,

There seems to be a typo in the docs - http://docs.gantry.org/gantry5/advanced/creating-layout-presets

`system.messages` and `system.content` should be changed to `system-messages` and `system-content`. It should be with a dash (-) instead of a dot (.)

**Comment by RyanMPierson** [comment]
On the contrary, we changed that today in preparation of Gantry 5.2. YAML version 2 has a number of changes, and this is one of them.

**Comment by RyanMPierson** [comment]
On second thought, after talking with @w00fz I might be in error. This was one of a bundle of changes we made to the doc today for 5.2, and it may very well be in error on the documentation. I'll follow up with @mahagr to confirm in the morning. Thanks for bringing to our attention.

**Comment by RyanMPierson** [comment]
Docs are fixed. Thanks again for bringing to our attention!
