### ISSUE TITLE
Documentation needs updating for "fullwidth (Flushed Content)" introduced in 5.2.0

### ISSUE THREAD

**Issue by ghost** [gantry/docs#67]
http://docs.gantry.org/gantry5/advanced/customizing-theme-files

The yaml needs updating as there is now another option:

0: Fullwidth (Boxed Content)
2: Fullwidth (Flushed Content)
1: Boxed

**Comment by RyanMPierson** [comment]
Docs are updated!

**Comment by ghost** [comment]
Confirmed - great :)
