### ISSUE TITLE
Issue in Gantry 5 - Advanced - Creating Layout Presets docs

### ISSUE THREAD

**Issue by tramber91** [gantry/docs#71]
Hi

in this sentence

You can also add custom images. For example, let's say we have example.png and we want to use it as the preset image. We would place it in /templates/TEMPLATE_DIR/custom/images/admin/layouts and reference it in the YAML file as gantry-media://images/admin/layouts/example.png

gantry-media://images/admin/layouts/example.png

should not be

gantry-media://admin/layouts/example.png

?

Bertrand

**Comment by RyanMPierson** [comment]
You are correct. Updated, and thank you!
