### ISSUE TITLE
Adding a new section in an existing layout

### ISSUE THREAD

**Issue by JoomFX** [gantry/docs#74]
@FrugalGeek Hey Ryan,

Could you please update the [Creating Layout Presets](http://docs.gantry.org/gantry5/advanced/creating-layout-presets) chapter in the documentation and add a new section called "Adding a new section to an existing layout" which explains the exact steps.

Just explain the whole process in details:
1. Adding the correct YAML code in the correct place:

```
/mainbottom/:
```
1. Which YAML file should be edited (the one in `root/templates/TEMPLATE_NAME/layouts` or the one in `root/templates/TEMPLATE_NAME/custom/config/xxx`)
2. The need to reload the layout in the Layout Manager and so on and so on.

Thanks :smile:

**Comment by RyanMPierson** [comment]
Would be happy to. Will probably be a few days because Thanksgiving, but if you wanted credit for it, feel free to make the change in a pull request and I'll approve it. Don't worry about being totally perfect in the editing, I can fix anything.

**Comment by mahagr** [comment]
If you are modifying existing theme, there are two options on what you can do (assuming Joomla):

1) You can edit existing outline in `templates/TEMPLATE_NAME/custom/config/xxx/layout.yaml`
2) You can modify existing or add new preset in `templates/TEMPLATE_NAME/custom/layouts/XXX.yaml`

Unless you are developing your own theme, do not modify anything outside `custom`.

Regarding to second question, if you modify outline, it should change by reloading the page; on presets you need to load the new layout.

**Comment by JoomFX** [comment]
@FrugalGeek Thanks Ryan! I'll wait, I just wanted to bring this to your attention.

@mahagr Thanks Matias! Yes, I know these things, you already taught me in the Gitter Chat (the last 8 months... wow, how time flies :open_mouth: )

I just want to have this added in the documentation (if possible) so I can just forward my customers there (lazy :smile: )

**Comment by RyanMPierson** [comment]
Howdy,

I have it done here: http://docs.gantry.org/gantry5/advanced/creating-layout-presets#adding-a-section-to-an-existing-layout-preset

Let me know if this works for you. Thanks for patience.
