### ISSUE TITLE
Update documentation regarding Advanced Theme Customization and adding Javascripts to the templates

### ISSUE THREAD

**Issue by N8Solutions** [gantry/docs#78]
The documentation regarding [Advanced Theme Customization](http://docs.gantry.org/gantry5/theme-development/theme-customization) should be updated to reflect the changes in `Settings` & `Page Settings`.  Adding `headroom.js` is used as an example of **Advanced Theme Customization** but it should be noted that it is now possible to do this in `Page Settings` without having to override the `page.html.twig` file.

I believe the [Blog post](http://gantry.org/blog/fixed-navigation) written by @JoomFX should be updated as well to show that there is a new way to **add the headroom.js script** to a template.

Also, a note should be added to both of those links to mention that if someone was to decide to implement a javascript using the method currently outlined in them, or has used it **(Like Me)**, instead of using the new method available in `Settings` & `Page Settings`, that when an update for the template is released, the `page.html.twig` file that is placed in the `THEME_DIR/custom/engine/templates/` directory as an override should be checked to see if the original was updated and to update the override accordingly otherwise problems with the template functionality will occur.

Having the aforementioned **Tip/Reminder** would have saved me 3 days of agony had I been aware of it.  Months ago I had **Implemented the Fixed Navigation/Header on scroll** using the information outlined in both of those articles.  Recently I ran in to an issue where when I added something to the `Before </body>` section in `Body Attributes` in `Page Settings` it was being ignored and not being "Implemented" on the front end.  As @w00fz helped me figure out this was due to the fact that the `page.html.twig` file I was using as an override to implement the `headroom.js` script was from a much older version of the Hydrogen Template and as such it was creating a problem with the `Before </body>` section in `Body Attributes`.

**Comment by RyanMPierson** [comment]
Updated documentation with two additional methods of achieving this. Will look in to updating blog posts and other areas of documentation presently.
