### ISSUE TITLE
Slight improvement suggestion for particle override section

### ISSUE THREAD

**Issue by ghost** [gantry/docs#80]
We encourage people to read this when creating particle overrides:
http://docs.gantry.org/gantry5/tutorials/overriding-particle-settings#overriding-particle-source-files

Some members are a little confused about the location of the original particle source files that they are trying to override. The docs correctly point out the location of CORE Gantry 5 particles as:
ROOT/media/gantry5/engines/nucleus/particles/
But... I think they should also point out the location of template specific particles too which is:
ROOT/templates/templatename/particles

I leave it to you how to word it :)

![2016-02-01_14-45-25](https://cloud.githubusercontent.com/assets/11683218/12720688/db458b14-c8f3-11e5-98ff-04dcf5626c70.png)

**Comment by RyanMPierson** [comment]
Done and done, thanks!
