### ISSUE TITLE
Troubleshooting entry: Third-party plugins interfering with platforms output

### ISSUE THREAD

**Issue by w00fz** [gantry/docs#87]
Very often we encounter users lamenting that assigning a specific outline to a specific menu item, doesn't get reflected on the front-end.
This usually ends up being caused by 3d party plugins (wordpress) or system plugins (joomla), that interfere with the output of the platform. In case of Gantry 5 specifically, it causes to render wrongly the outline, falling back to the default one instead of the supposed assigned one.

An entry in the Troubleshooting page for Gantry Docs could allow us to easily point people with the same issue to.

Recently this came to our attention with a site @hennysmafter brought up in which the plugin `System - JCK Modal` caused this behavior.

I know there are other ones that the moderators (specifically @marktaylor46) have came across with. Perhaps it could be a good idea to somehow list them. If not in the docs directly, even just adding a note to this issue could be alright.

Cheers.

**Comment by RyanMPierson** [comment]
Done and done. Thanks! Will add more specific ones over time.
