### ISSUE TITLE
Review documentation on layout yaml files

### ISSUE THREAD

**Issue by mahagr** [gantry/docs#95]
Looks like our document is missing some finer details. Review them with me. :)

**Comment by newkind** [comment]
LOL you won't figure it out later what you meant :D

Support for extra stuff like all posibilities of `type` `subtype` `title` etc.

**Comment by mahagr** [comment]
LOL You are underestimating my memory (or i'm overestimating it).

**Comment by RyanMPierson** [comment]
Done and Done!
