### ISSUE TITLE
Document Joomla ACL

### ISSUE THREAD

**Issue by mahagr** [gantry/docs#96]
Gantry 5.2.14 now obeys Joomla ACL and uses menu and template ACL to allow and hide the same actions as Joomla would.

**Comment by RyanMPierson** [comment]
This is a bit cryptic. We need to document what part of this exactly? Also, are we mentioning it or do we need to do some detailed tutorials?

**Comment by mahagr** [comment]
This issue is mostly a note to myself. Basically by obeying Joomla ACL I mean that if you prevent user from editing menus, he will also not see menu editor in Gantry. Or if you prevent user from deleting outlines, that option will be hidden and prevented from Gantry...
